############################################
### PACIENTES — API SANIDAD
############################################

### GET /api/patients — Recupera todos los pacientes
GET http://localhost:3000/api/patients


### GET /api/patients/:id — Recupera un paciente por ID
GET http://localhost:3000/api/patients/1


### GET /api/patients/:id — NOT FOUND (404)
GET http://localhost:3000/api/patients/999


### GET /api/patients/:id?relations=true — Paciente + su médico (N:1)
GET http://localhost:3000/api/patients/1?relations=true


### POST /api/patients — Crear un paciente
POST http://localhost:3000/api/patients
Content-Type: application/json

{
  "name": "Juan",
  "surname": "Pérez",
  "birth_date": "1990-05-12",
  "email": "juan@example.com",
  "phone": "600123123",
  "doctor_id": 1
}


### POST /api/patients — Ejemplo 2
POST http://localhost:3000/api/patients
Content-Type: application/json

{
  "name": "Ana",
  "surname": "Gómez",
  "birth_date": "1985-10-20",
  "email": "ana@example.com",
  "phone": "600987987",
  "doctor_id": 2
}


### PUT /api/patients/:id — Actualizar un paciente
PUT http://localhost:3000/api/patients/1
Content-Type: application/json

{
  "name": "Juan",
  "surname": "Pérez Actualizado",
  "birth_date": "1990-05-12",
  "email": "juan.updated@example.com",
  "phone": "600111222",
  "doctor_id": 2
}


### PUT /api/patients/:id — NOT FOUND (404)
PUT http://localhost:3000/api/patients/999
Content-Type: application/json

{
  "name": "Paciente",
  "surname": "Inexistente",
  "birth_date": "2000-01-01",
  "email": "no@existe.com",
  "phone": "000000000",
  "doctor_id": 1
}


### DELETE /api/patients/:id — Eliminar un paciente
DELETE http://localhost:3000/api/patients/1


### DELETE /api/patients/:id — NOT FOUND (404)
DELETE http://localhost:3000/api/patients/999

### GET /api/patients?startDate=1980-01-01&endDate=1990-12-31 — Pacientes nacidos entre 1980 y 1990
GET http://localhost:3000/api/patients?startDate=1980-01-01&endDate=1990-12-31
